export const SEARCH_BEERS = 'SEARCH_BEERS';
export const GET_RANDOM_BEER = 'GET_RANDOM_BEER';
export const SET_LOADING = 'SET_LOADING';
export const SEARCH_BEER_LOADING = 'SEARCH_BEER_LOADING';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
